### PR TITLE
Injectable Relations

### PR DESCRIPTION
**Pull request by recursivetree**
## Use Case
Model relations are really nice. But when writing plugins, there is one annoying thing: You can't add relations to the core models. 

For example, seat-info has articles that belong to a user. Therefore I add a user relation to the article model. Adding a relation the other way round is not possible. You can always work around this by writing something like:
```php
// get a user with relation
$user = $some->path->to->a->user->model;
// plugin boundary
$plugin_thing = PluginThing::where("user_id",$user->id)->first();
//then you can continue with relations
$other_plugin_thing = $plugin_thing->other_plugin_thing;
```
but this looks much better:
```php
$other_plugin_thing = $some->path->to->a->user->model->plugin_thing->other_plugin_thing;
```

## Solution
The idea is to have a mechanism to inject relations into core models. 

With this PR, all core models should start extending from `\Seat\Services\Models\ExtensibleModel` instead of from `Illuminate\Database\Eloquent\Model`

In it's service provider, a plugin can then inject relations into a model:
```php
class TestingServiceProvider extends AbstractSeatPlugin
{
    public function boot()
    {
        UserSetting::injectRelationsFrom(UserSettingExtension::class);
    }
}
```

The relations to be injected can be found in an extension class:
```php
class UserSettingExtension
{
    // note how it looks almost like a normal relation, except that we act on $model instead of $this
    public function user(UserSetting $model){
        return $model->belongsTo(User::class,"user_id","id");
    }
}
```

From then on, `UserSetting` behaves as if it has a `user` relation:
```php
$setting = UserSetting::first();
// use the injected relation like any other
$name = $setting->user->name;
```

## Other Advantages
Because seat is split into multiple packages, some relations can't exist without introducing dependencies, for example `services` doesn't depend on `web`, so there can't be a `user` relation from `UserSetting` in `services` to `User` in `web`. With this PR, we could inject such a relation from `web` into `services`.

## Work from here on
- @warlof focus on SeAT 5, this doesn't break anything, so we can deliver it with seat 5.1
- I'll leave this up to collect feedback before opening PRs to change the model class in all models in other repos
- I tried to add testing, but it seems broken and outdated. I couldn't get DB tests working.

### CODE REVIEW

**Comment by recursivetree** [comment]
Ignore my comment about testing, I based it on an old branch

**Comment by warlof** [comment]
> Ignore my comment about testing, I based it on an old branch

Tests were broken, I had fixed them few days ago while tagging packages 🤫
I like the concept, might need some extra check to ensure for exemple, the model is working with Tara datable Factory
Also might try to ensure we have no alternative regarding Laravel core rewrite that might cause troubles or extra work with upgrades

Regarding your exception testing, you can use this implementation instead https://docs.phpunit.de/en/10.2/writing-tests-for-phpunit.html#writing-tests-for-phpunit-exceptions-examples-exceptiontest-php

**Comment by recursivetree** [comment]
I got the tests sorted, but it's not that easy to run them in a docker development environment. I think we can improve things there, but that's for another discussion.

What do you mean with `Tara datable Factory`? DataTables as used in the frontend? Laravel factories? Googling it didn't yield anything.

Regarding upgradability going forward, I agree, there is some risk. However, we now have tests testing wether it works, and the copied laravel code is rather small.

**Comment by warlof** [comment]
> I got the tests sorted, but it's not that easy to run them in a docker development environment. I think we can improve things there, but that's for another discussion.
> 
> What do you mean with `Tara datable Factory`? DataTables as used in the frontend? Laravel factories? Googling it didn't yield anything.
> 
> Regarding upgradability going forward, I agree, there is some risk. However, we now have tests testing wether it works, and the copied laravel code is rather small.

Oops, made a typo while typing on mobile
I was indeed talking about Yajra Datable library

**Comment by recursivetree** [comment]
Sure, I can add tests with yajra datatables. What kind of test do you have in mind? 

Additionally, I added a test for eager loading with `Model::with`.

**Comment by recursivetree** [comment]
I guess you need a browser to test it, or is there some way to statically render it server-side?

Maybe it be enough to create a datatable using injectable relations and manually test whether it works? I suspect if something breaks, it should affect the normal tests too, or otherwise we will notice it relatively soon assuming the feature will be used.

**Comment by Crypta-Eve** [comment]
I have had look into it and there are end to end things we can do but I think its beyond the scope of what we require. As such, I am in favour of merging.

**Pull request merged**
