### PR TITLE
fix(dashboard): Avoid eager load usage on mining stats leading to timeout

### PR DESCRIPTION
**Pull request by warlof**

### CODE REVIEW

**Comment by herpaderpaldent** [comment]
Hey @warlof 

I noticed that with your current 'fix' eager-loading PRs something got forgotten. Maybe i am just to blind to see it.

by merging this PR https://github.com/eveseat/eveapi/pull/123/files you have removed the 'set' method of a historic price. 
Whenever the price should get be leftjoinend there is no entry that could actually be leftjoined and will result in multiple zero lines. 

In `MiningLedgerController` this was the line that did the setting/getting https://github.com/eveseat/web/commit/794edd4e823bcdc4cc0d99dc05e6c11ea9e9c8e0#diff-22011822c62a614039762bc1627bbd3bL55 

in `Stats` this is removing the setting/getting https://github.com/eveseat/services/pull/68/files#diff-0a192c3f7ec8a7bcc3181ae3229a931bL55

**Comment by herpaderpaldent** [comment]
maybe it would be enough to move this line https://github.com/eveseat/eveapi/blob/master/src/Jobs/Industry/Character/Mining.php#L121

before or after the `if ($delta_quantity != 0)` clause?

**Comment by warlof** [comment]
> 
> 
> Hey @warlof
> 
> I noticed that with your current 'fix' eager-loading PRs something got forgotten. Maybe i am just to blind to see it.
> 
> by merging this PR https://github.com/eveseat/eveapi/pull/123/files you have removed the 'set' method of a historic price.
> Whenever the price should get be leftjoinend there is no entry that could actually be leftjoined and will result in multiple zero lines.
> 
> In `MiningLedgerController` this was the line that did the setting/getting [eveseat/web@794edd4#diff-22011822c62a614039762bc1627bbd3bL55](https://github.com/eveseat/web/commit/794edd4e823bcdc4cc0d99dc05e6c11ea9e9c8e0#diff-22011822c62a614039762bc1627bbd3bL55)
> 
> in `Stats` this is removing the setting/getting https://github.com/eveseat/services/pull/68/files#diff-0a192c3f7ec8a7bcc3181ae3229a931bL55

I don't see any set on lines you're targeting - only get and aggregates. Are you sure about this ?
Furthermore, why want you move this line outside of delta update ?

In case you don't have any delta, that just mean you have up to date data. And you won't update prices from already persisted information.

**Comment by herpaderpaldent** [comment]
by merging this we really should settle on: https://github.com/eveseat/eveapi/pull/127 until the 22nd

**Pull request merged**
