### PR TITLE
update issuer claim to align with incoming ccp change

### PR DESCRIPTION
**Pull request by justindh**
https://forums.eveonline.com/t/eve-sso-jwt-token-update-on-19-october-11-00-utc/424277

### CODE REVIEW

**Comment by justindh** [comment]
untested as the change hasnt been implemented yet

**Review by leonjza — APPROVED** [review]

**Comment by wfjsw** [comment]
Does iss() actually accepts array, no?

https://github.com/web-token/jwt-easy/blob/9aa087db5995e02ccf157716943232fca47a9ab2/AbstractLoader.php#L91-L94

**Comment by Crypta-Eve** [comment]
Can confirm that this will not work in this version. Suggest closing in favour of #172

**Comment by recursivetree** [comment]
this can be closed

**Pull request closed without merging**
